### ISSUE TITLE
Shorts in analog layout.

### ISSUE THREAD

**Issue by d-m-bailey** [andylithia/Project-Yatsuhashi-Chip1#1]
I'm detecting shorts in the analog layout. Do you have a hierarchical version around that might be easier to check?
```
"Extracting analog_area into analog_area.ext:
Warning:  Ports ""vdda1"" and ""vssa2"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""vssd2"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""analog_la_out[11]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""analog_la_out[10]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_high[1]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""vccd2"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_analog[10]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_analog[8]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_low[2]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_low[1]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_high[2]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""vssa1"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""vccd1"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_low[0]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_clamp_high[0]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_analog[3]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_analog[2]"" are electrically shorted.
Warning:  Ports ""vdda1"" and ""io_analog[1]"" are electrically shorted."
```

**Comment by AL-255** [comment]
Hi Bailey, Thanks a lot for the comment. I'm aware that most of those shorts are inductors. but the shorts on the power rail is indeed unexpected. The top-level LVS is too slow to run on my setup... I'll keep you updated.

**Comment by d-m-bailey** [comment]
On other projects, I've developed a solution for LVS with inductors. The inductors need to be in separate cells though. They need pins and a metal short layer and then I black box them so they match the schematic.

Looks like the gds/analog_area_v3r.gds.gz file contains a hierarchical version of the layout and the analog schematic is in xschem. I'll see what I can do.

**Comment by AL-255** [comment]
Thanks, I did the black box approach when extracting the subcells. But not for the top level. I've identified two cases where the ground shield touches another wire. I have to be honest that the PA, which is rushed, is especially problematic. Thank you so much for bringing this up. I'll try to fix them while we can still touch the MPW7 gds.

**Comment by d-m-bailey** [comment]
What about these drc errors? 
<img width="1062" alt="pointcontact" src="https://user-images.githubusercontent.com/8349634/195485179-307d42d4-9ad7-4df8-a72d-bdbbf0fc52c9.png">

**Comment by AL-255** [comment]
@d-m-bailey Those are fixed manually after uploading the GDS to the eFabless platform. I edited the GDS file using the Klayout installation in their "Galaxy" online environment

**Comment by andylithia** [comment]
Some shorts have been removed. We spotted a connection mistake at the decoupling MIM array on the right-hand side, and some control wires are touching the ground shield. Right now the hierarchical PEX returns a satisfying result, have to run it again with a flattened one.

**Comment by AL-255** [comment]
The issue has been resolved. Most of them are caused by the additional ESD cell, which is a last-minute change
